//玩家目前状态
const PLAYER_STATUS = {
 SET_CUR_HP: 'SET_CUR_HP',
 SET_MAX_HP: 'SET_MAX_HP',
 SET_USERNAME: 'SET_USERNAME',
 SET_PLAYER_BUFF: 'SET_PLAYER_BUFF',
 SET_UNLOCK_SOIL: 'SET_UNLOCK_SOIL',
};

const SYSTEM = {
 SET_DICT: 'SET_DICT',
};

export { PLAYER_STATUS, SYSTEM };
